---
openapi: 3.0.1
info:
  title: product-service-dev
  version: 1.0.0
servers:
- url: https://1ddl9jja42.execute-api.eu-west-1.amazonaws.com/{basePath}
  variables:
    basePath:
      default: dev
paths:
  /product/{id}:
    get:
      operationId: getProductById
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Product not found
  /products:
    get:
      operationId: getProductsList
      responses:
        "200":
          description: 200 response
          headers:
            Access-Control-Allow-Origin:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Methods:
              style: simple
              explode: false
              schema:
                type: string
            Access-Control-Allow-Headers:
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64
    Products:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
